run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Core linters
    - govet
    - typecheck
    - gofmt
  disable:
    # Disable strict linters for now - can enable later
    - errcheck
    - unused
    - ineffassign
    - staticcheck
    - gosimple
    - unparam

linters-settings:
  govet:
    enable-all: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unusedresult

issues:
  exclude-rules:
    # Exclude generated files
    - path: _templ\.go
      linters:
        - all
    - path: \.pb\.go
      linters:
        - all
    # Exclude test files from formatting checks
    - path: _test\.go
      linters:
        - gofmt
    # Exclude property test files
    - path: _property_test\.go
      linters:
        - all
