// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/controlplane.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_UNKNOWN       CommandType = 0
	CommandType_COMMAND_DEPLOY        CommandType = 1
	CommandType_COMMAND_STOP          CommandType = 2
	CommandType_COMMAND_RESTART       CommandType = 3
	CommandType_COMMAND_UPDATE_CONFIG CommandType = 4
	CommandType_COMMAND_STREAM_LOGS   CommandType = 5
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_UNKNOWN",
		1: "COMMAND_DEPLOY",
		2: "COMMAND_STOP",
		3: "COMMAND_RESTART",
		4: "COMMAND_UPDATE_CONFIG",
		5: "COMMAND_STREAM_LOGS",
	}
	CommandType_value = map[string]int32{
		"COMMAND_UNKNOWN":       0,
		"COMMAND_DEPLOY":        1,
		"COMMAND_STOP":          2,
		"COMMAND_RESTART":       3,
		"COMMAND_UPDATE_CONFIG": 4,
		"COMMAND_STREAM_LOGS":   5,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_controlplane_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_api_proto_controlplane_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{0}
}

type CPBuildType int32

const (
	CPBuildType_CP_BUILD_TYPE_UNKNOWN CPBuildType = 0
	CPBuildType_CP_BUILD_TYPE_OCI     CPBuildType = 1
	CPBuildType_CP_BUILD_TYPE_NIX     CPBuildType = 2
)

// Enum value maps for CPBuildType.
var (
	CPBuildType_name = map[int32]string{
		0: "CP_BUILD_TYPE_UNKNOWN",
		1: "CP_BUILD_TYPE_OCI",
		2: "CP_BUILD_TYPE_NIX",
	}
	CPBuildType_value = map[string]int32{
		"CP_BUILD_TYPE_UNKNOWN": 0,
		"CP_BUILD_TYPE_OCI":     1,
		"CP_BUILD_TYPE_NIX":     2,
	}
)

func (x CPBuildType) Enum() *CPBuildType {
	p := new(CPBuildType)
	*p = x
	return p
}

func (x CPBuildType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CPBuildType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_controlplane_proto_enumTypes[1].Descriptor()
}

func (CPBuildType) Type() protoreflect.EnumType {
	return &file_api_proto_controlplane_proto_enumTypes[1]
}

func (x CPBuildType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CPBuildType.Descriptor instead.
func (CPBuildType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{1}
}

type DeploymentStatus int32

const (
	DeploymentStatus_STATUS_UNKNOWN  DeploymentStatus = 0
	DeploymentStatus_STATUS_PENDING  DeploymentStatus = 1
	DeploymentStatus_STATUS_PULLING  DeploymentStatus = 2
	DeploymentStatus_STATUS_STARTING DeploymentStatus = 3
	DeploymentStatus_STATUS_RUNNING  DeploymentStatus = 4
	DeploymentStatus_STATUS_STOPPING DeploymentStatus = 5
	DeploymentStatus_STATUS_STOPPED  DeploymentStatus = 6
	DeploymentStatus_STATUS_FAILED   DeploymentStatus = 7
)

// Enum value maps for DeploymentStatus.
var (
	DeploymentStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_PENDING",
		2: "STATUS_PULLING",
		3: "STATUS_STARTING",
		4: "STATUS_RUNNING",
		5: "STATUS_STOPPING",
		6: "STATUS_STOPPED",
		7: "STATUS_FAILED",
	}
	DeploymentStatus_value = map[string]int32{
		"STATUS_UNKNOWN":  0,
		"STATUS_PENDING":  1,
		"STATUS_PULLING":  2,
		"STATUS_STARTING": 3,
		"STATUS_RUNNING":  4,
		"STATUS_STOPPING": 5,
		"STATUS_STOPPED":  6,
		"STATUS_FAILED":   7,
	}
)

func (x DeploymentStatus) Enum() *DeploymentStatus {
	p := new(DeploymentStatus)
	*p = x
	return p
}

func (x DeploymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_controlplane_proto_enumTypes[2].Descriptor()
}

func (DeploymentStatus) Type() protoreflect.EnumType {
	return &file_api_proto_controlplane_proto_enumTypes[2]
}

func (x DeploymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentStatus.Descriptor instead.
func (DeploymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{2}
}

type CPLogLevel int32

const (
	CPLogLevel_CP_LOG_UNKNOWN CPLogLevel = 0
	CPLogLevel_CP_LOG_DEBUG   CPLogLevel = 1
	CPLogLevel_CP_LOG_INFO    CPLogLevel = 2
	CPLogLevel_CP_LOG_WARN    CPLogLevel = 3
	CPLogLevel_CP_LOG_ERROR   CPLogLevel = 4
)

// Enum value maps for CPLogLevel.
var (
	CPLogLevel_name = map[int32]string{
		0: "CP_LOG_UNKNOWN",
		1: "CP_LOG_DEBUG",
		2: "CP_LOG_INFO",
		3: "CP_LOG_WARN",
		4: "CP_LOG_ERROR",
	}
	CPLogLevel_value = map[string]int32{
		"CP_LOG_UNKNOWN": 0,
		"CP_LOG_DEBUG":   1,
		"CP_LOG_INFO":    2,
		"CP_LOG_WARN":    3,
		"CP_LOG_ERROR":   4,
	}
)

func (x CPLogLevel) Enum() *CPLogLevel {
	p := new(CPLogLevel)
	*p = x
	return p
}

func (x CPLogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CPLogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_controlplane_proto_enumTypes[3].Descriptor()
}

func (CPLogLevel) Type() protoreflect.EnumType {
	return &file_api_proto_controlplane_proto_enumTypes[3]
}

func (x CPLogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CPLogLevel.Descriptor instead.
func (CPLogLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{3}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_controlplane_proto_enumTypes[4].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_api_proto_controlplane_proto_enumTypes[4]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{1, 0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=controlplane.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

type NodeInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname          string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address           string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	GrpcPort          int32                  `protobuf:"varint,4,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	Resources         *ResourceMetrics       `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	CachedPaths       []string               `protobuf:"bytes,6,rep,name=cached_paths,json=cachedPaths,proto3" json:"cached_paths,omitempty"`
	AvailableSlots    int32                  `protobuf:"varint,7,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	ActiveDeployments int32                  `protobuf:"varint,8,opt,name=active_deployments,json=activeDeployments,proto3" json:"active_deployments,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_api_proto_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *NodeInfo) GetResources() *ResourceMetrics {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *NodeInfo) GetCachedPaths() []string {
	if x != nil {
		return x.CachedPaths
	}
	return nil
}

func (x *NodeInfo) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

func (x *NodeInfo) GetActiveDeployments() int32 {
	if x != nil {
		return x.ActiveDeployments
	}
	return 0
}

type ResourceMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuTotal        float64                `protobuf:"fixed64,1,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuAvailable    float64                `protobuf:"fixed64,2,opt,name=cpu_available,json=cpuAvailable,proto3" json:"cpu_available,omitempty"`
	MemoryTotal     int64                  `protobuf:"varint,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryAvailable int64                  `protobuf:"varint,4,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	DiskTotal       int64                  `protobuf:"varint,5,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskAvailable   int64                  `protobuf:"varint,6,opt,name=disk_available,json=diskAvailable,proto3" json:"disk_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceMetrics) Reset() {
	*x = ResourceMetrics{}
	mi := &file_api_proto_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMetrics) ProtoMessage() {}

func (x *ResourceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMetrics.ProtoReflect.Descriptor instead.
func (*ResourceMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceMetrics) GetCpuTotal() float64 {
	if x != nil {
		return x.CpuTotal
	}
	return 0
}

func (x *ResourceMetrics) GetCpuAvailable() float64 {
	if x != nil {
		return x.CpuAvailable
	}
	return 0
}

func (x *ResourceMetrics) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *ResourceMetrics) GetMemoryAvailable() int64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *ResourceMetrics) GetDiskTotal() int64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *ResourceMetrics) GetDiskAvailable() int64 {
	if x != nil {
		return x.DiskAvailable
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *RegisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Config        *NodeConfig            `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *NodeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type NodeConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,1,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	MaxConcurrentDeployments int32                  `protobuf:"varint,2,opt,name=max_concurrent_deployments,json=maxConcurrentDeployments,proto3" json:"max_concurrent_deployments,omitempty"`
	LogBufferSize            int32                  `protobuf:"varint,3,opt,name=log_buffer_size,json=logBufferSize,proto3" json:"log_buffer_size,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_api_proto_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *NodeConfig) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *NodeConfig) GetMaxConcurrentDeployments() int32 {
	if x != nil {
		return x.MaxConcurrentDeployments
	}
	return 0
}

func (x *NodeConfig) GetLogBufferSize() int32 {
	if x != nil {
		return x.LogBufferSize
	}
	return 0
}

type HeartbeatRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodeId    string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeInfo  *NodeInfo              `protobuf:"bytes,2,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// draining indicates the node is shutting down and should not receive new deployments
	Draining      bool `protobuf:"varint,4,opt,name=draining,proto3" json:"draining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WatchCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCommandsRequest) Reset() {
	*x = WatchCommandsRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCommandsRequest) ProtoMessage() {}

func (x *WatchCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCommandsRequest.ProtoReflect.Descriptor instead.
func (*WatchCommandsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *WatchCommandsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WatchCommandsRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type DeploymentCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type      CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=controlplane.CommandType" json:"type,omitempty"`
	Deadline  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*DeploymentCommand_Deploy
	//	*DeploymentCommand_Stop
	//	*DeploymentCommand_Restart
	//	*DeploymentCommand_UpdateConfig
	//	*DeploymentCommand_StreamLogs
	Command       isDeploymentCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentCommand) Reset() {
	*x = DeploymentCommand{}
	mi := &file_api_proto_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentCommand) ProtoMessage() {}

func (x *DeploymentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentCommand.ProtoReflect.Descriptor instead.
func (*DeploymentCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *DeploymentCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *DeploymentCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_UNKNOWN
}

func (x *DeploymentCommand) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *DeploymentCommand) GetCommand() isDeploymentCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *DeploymentCommand) GetDeploy() *CPDeployRequest {
	if x != nil {
		if x, ok := x.Command.(*DeploymentCommand_Deploy); ok {
			return x.Deploy
		}
	}
	return nil
}

func (x *DeploymentCommand) GetStop() *CPStopRequest {
	if x != nil {
		if x, ok := x.Command.(*DeploymentCommand_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *DeploymentCommand) GetRestart() *CPRestartRequest {
	if x != nil {
		if x, ok := x.Command.(*DeploymentCommand_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *DeploymentCommand) GetUpdateConfig() *CPUpdateConfigRequest {
	if x != nil {
		if x, ok := x.Command.(*DeploymentCommand_UpdateConfig); ok {
			return x.UpdateConfig
		}
	}
	return nil
}

func (x *DeploymentCommand) GetStreamLogs() *CPLogStreamRequest {
	if x != nil {
		if x, ok := x.Command.(*DeploymentCommand_StreamLogs); ok {
			return x.StreamLogs
		}
	}
	return nil
}

type isDeploymentCommand_Command interface {
	isDeploymentCommand_Command()
}

type DeploymentCommand_Deploy struct {
	Deploy *CPDeployRequest `protobuf:"bytes,10,opt,name=deploy,proto3,oneof"`
}

type DeploymentCommand_Stop struct {
	Stop *CPStopRequest `protobuf:"bytes,11,opt,name=stop,proto3,oneof"`
}

type DeploymentCommand_Restart struct {
	Restart *CPRestartRequest `protobuf:"bytes,12,opt,name=restart,proto3,oneof"`
}

type DeploymentCommand_UpdateConfig struct {
	UpdateConfig *CPUpdateConfigRequest `protobuf:"bytes,13,opt,name=update_config,json=updateConfig,proto3,oneof"`
}

type DeploymentCommand_StreamLogs struct {
	StreamLogs *CPLogStreamRequest `protobuf:"bytes,14,opt,name=stream_logs,json=streamLogs,proto3,oneof"`
}

func (*DeploymentCommand_Deploy) isDeploymentCommand_Command() {}

func (*DeploymentCommand_Stop) isDeploymentCommand_Command() {}

func (*DeploymentCommand_Restart) isDeploymentCommand_Command() {}

func (*DeploymentCommand_UpdateConfig) isDeploymentCommand_Command() {}

func (*DeploymentCommand_StreamLogs) isDeploymentCommand_Command() {}

type CPDeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Artifact      string                 `protobuf:"bytes,4,opt,name=artifact,proto3" json:"artifact,omitempty"`
	BuildType     CPBuildType            `protobuf:"varint,5,opt,name=build_type,json=buildType,proto3,enum=controlplane.CPBuildType" json:"build_type,omitempty"`
	Config        *CPDeploymentConfig    `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPDeployRequest) Reset() {
	*x = CPDeployRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPDeployRequest) ProtoMessage() {}

func (x *CPDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPDeployRequest.ProtoReflect.Descriptor instead.
func (*CPDeployRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *CPDeployRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CPDeployRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CPDeployRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CPDeployRequest) GetArtifact() string {
	if x != nil {
		return x.Artifact
	}
	return ""
}

func (x *CPDeployRequest) GetBuildType() CPBuildType {
	if x != nil {
		return x.BuildType
	}
	return CPBuildType_CP_BUILD_TYPE_UNKNOWN
}

func (x *CPDeployRequest) GetConfig() *CPDeploymentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CPDeploymentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceTier  string                 `protobuf:"bytes,1,opt,name=resource_tier,json=resourceTier,proto3" json:"resource_tier,omitempty"`
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DependsOn     []string               `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	HealthCheck   *CPHealthCheckConfig   `protobuf:"bytes,5,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPDeploymentConfig) Reset() {
	*x = CPDeploymentConfig{}
	mi := &file_api_proto_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPDeploymentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPDeploymentConfig) ProtoMessage() {}

func (x *CPDeploymentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPDeploymentConfig.ProtoReflect.Descriptor instead.
func (*CPDeploymentConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *CPDeploymentConfig) GetResourceTier() string {
	if x != nil {
		return x.ResourceTier
	}
	return ""
}

func (x *CPDeploymentConfig) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *CPDeploymentConfig) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *CPDeploymentConfig) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *CPDeploymentConfig) GetHealthCheck() *CPHealthCheckConfig {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *CPDeploymentConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CPHealthCheckConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Path               string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Port               int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	IntervalSeconds    int32                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	TimeoutSeconds     int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	HealthyThreshold   int32                  `protobuf:"varint,5,opt,name=healthy_threshold,json=healthyThreshold,proto3" json:"healthy_threshold,omitempty"`
	UnhealthyThreshold int32                  `protobuf:"varint,6,opt,name=unhealthy_threshold,json=unhealthyThreshold,proto3" json:"unhealthy_threshold,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CPHealthCheckConfig) Reset() {
	*x = CPHealthCheckConfig{}
	mi := &file_api_proto_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPHealthCheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPHealthCheckConfig) ProtoMessage() {}

func (x *CPHealthCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPHealthCheckConfig.ProtoReflect.Descriptor instead.
func (*CPHealthCheckConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *CPHealthCheckConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CPHealthCheckConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CPHealthCheckConfig) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *CPHealthCheckConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CPHealthCheckConfig) GetHealthyThreshold() int32 {
	if x != nil {
		return x.HealthyThreshold
	}
	return 0
}

func (x *CPHealthCheckConfig) GetUnhealthyThreshold() int32 {
	if x != nil {
		return x.UnhealthyThreshold
	}
	return 0
}

type CPStopRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId   string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Force          bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CPStopRequest) Reset() {
	*x = CPStopRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPStopRequest) ProtoMessage() {}

func (x *CPStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPStopRequest.ProtoReflect.Descriptor instead.
func (*CPStopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *CPStopRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CPStopRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *CPStopRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CPRestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPRestartRequest) Reset() {
	*x = CPRestartRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPRestartRequest) ProtoMessage() {}

func (x *CPRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPRestartRequest.ProtoReflect.Descriptor instead.
func (*CPRestartRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{15}
}

func (x *CPRestartRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type CPUpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Config        *CPDeploymentConfig    `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUpdateConfigRequest) Reset() {
	*x = CPUpdateConfigRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUpdateConfigRequest) ProtoMessage() {}

func (x *CPUpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*CPUpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{16}
}

func (x *CPUpdateConfigRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CPUpdateConfigRequest) GetConfig() *CPDeploymentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CPLogStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	TailLines     int32                  `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	Follow        bool                   `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	ServiceFilter string                 `protobuf:"bytes,5,opt,name=service_filter,json=serviceFilter,proto3" json:"service_filter,omitempty"`
	LevelFilter   CPLogLevel             `protobuf:"varint,6,opt,name=level_filter,json=levelFilter,proto3,enum=controlplane.CPLogLevel" json:"level_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPLogStreamRequest) Reset() {
	*x = CPLogStreamRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPLogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPLogStreamRequest) ProtoMessage() {}

func (x *CPLogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPLogStreamRequest.ProtoReflect.Descriptor instead.
func (*CPLogStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{17}
}

func (x *CPLogStreamRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CPLogStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *CPLogStreamRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *CPLogStreamRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *CPLogStreamRequest) GetServiceFilter() string {
	if x != nil {
		return x.ServiceFilter
	}
	return ""
}

func (x *CPLogStreamRequest) GetLevelFilter() CPLogLevel {
	if x != nil {
		return x.LevelFilter
	}
	return CPLogLevel_CP_LOG_UNKNOWN
}

type StatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        DeploymentStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=controlplane.DeploymentStatus" json:"status,omitempty"`
	ContainerId   string                 `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExitCode      int32                  `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ResourceUsage *ResourceUsage         `protobuf:"bytes,9,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_api_proto_controlplane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{18}
}

func (x *StatusReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatusReport) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *StatusReport) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *StatusReport) GetStatus() DeploymentStatus {
	if x != nil {
		return x.Status
	}
	return DeploymentStatus_STATUS_UNKNOWN
}

func (x *StatusReport) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StatusReport) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StatusReport) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StatusReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StatusReport) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

type ResourceUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent     float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes    int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	NetworkRxBytes int64                  `protobuf:"varint,3,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes int64                  `protobuf:"varint,4,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_api_proto_controlplane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{19}
}

func (x *ResourceUsage) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsage) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceUsage) GetNetworkRxBytes() int64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *ResourceUsage) GetNetworkTxBytes() int64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_controlplane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{20}
}

func (x *StatusResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type CPLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         CPLogLevel             `protobuf:"varint,5,opt,name=level,proto3,enum=controlplane.CPLogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPLogEntry) Reset() {
	*x = CPLogEntry{}
	mi := &file_api_proto_controlplane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPLogEntry) ProtoMessage() {}

func (x *CPLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPLogEntry.ProtoReflect.Descriptor instead.
func (*CPLogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{21}
}

func (x *CPLogEntry) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CPLogEntry) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *CPLogEntry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CPLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CPLogEntry) GetLevel() CPLogLevel {
	if x != nil {
		return x.Level
	}
	return CPLogLevel_CP_LOG_UNKNOWN
}

func (x *CPLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CPLogEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PushLogsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntriesReceived int64                  `protobuf:"varint,1,opt,name=entries_received,json=entriesReceived,proto3" json:"entries_received,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushLogsResponse) Reset() {
	*x = PushLogsResponse{}
	mi := &file_api_proto_controlplane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogsResponse) ProtoMessage() {}

func (x *PushLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogsResponse.ProtoReflect.Descriptor instead.
func (*PushLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{22}
}

func (x *PushLogsResponse) GetEntriesReceived() int64 {
	if x != nil {
		return x.EntriesReceived
	}
	return 0
}

var File_api_proto_controlplane_proto protoreflect.FileDescriptor

const file_api_proto_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/controlplane.proto\x12\fcontrolplane\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x9a\x01\n" +
	"\x13HealthCheckResponse\x12G\n" +
	"\x06status\x18\x01 \x01(\x0e2/.controlplane.HealthCheckResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"\xa5\x02\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1b\n" +
	"\tgrpc_port\x18\x04 \x01(\x05R\bgrpcPort\x12;\n" +
	"\tresources\x18\x05 \x01(\v2\x1d.controlplane.ResourceMetricsR\tresources\x12!\n" +
	"\fcached_paths\x18\x06 \x03(\tR\vcachedPaths\x12'\n" +
	"\x0favailable_slots\x18\a \x01(\x05R\x0eavailableSlots\x12-\n" +
	"\x12active_deployments\x18\b \x01(\x05R\x11activeDeployments\"\xe7\x01\n" +
	"\x0fResourceMetrics\x12\x1b\n" +
	"\tcpu_total\x18\x01 \x01(\x01R\bcpuTotal\x12#\n" +
	"\rcpu_available\x18\x02 \x01(\x01R\fcpuAvailable\x12!\n" +
	"\fmemory_total\x18\x03 \x01(\x03R\vmemoryTotal\x12)\n" +
	"\x10memory_available\x18\x04 \x01(\x03R\x0fmemoryAvailable\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x05 \x01(\x03R\tdiskTotal\x12%\n" +
	"\x0edisk_available\x18\x06 \x01(\x03R\rdiskAvailable\"e\n" +
	"\x0fRegisterRequest\x123\n" +
	"\tnode_info\x18\x01 \x01(\v2\x16.controlplane.NodeInfoR\bnodeInfo\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"\x91\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x120\n" +
	"\x06config\x18\x04 \x01(\v2\x18.controlplane.NodeConfigR\x06config\"\xb0\x01\n" +
	"\n" +
	"NodeConfig\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x01 \x01(\x05R\x18heartbeatIntervalSeconds\x12<\n" +
	"\x1amax_concurrent_deployments\x18\x02 \x01(\x05R\x18maxConcurrentDeployments\x12&\n" +
	"\x0flog_buffer_size\x18\x03 \x01(\x05R\rlogBufferSize\"\xb6\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x123\n" +
	"\tnode_info\x18\x02 \x01(\v2\x16.controlplane.NodeInfoR\bnodeInfo\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bdraining\x18\x04 \x01(\bR\bdraining\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\x14WatchCommandsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"\xdd\x03\n" +
	"\x11DeploymentCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.controlplane.CommandTypeR\x04type\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x127\n" +
	"\x06deploy\x18\n" +
	" \x01(\v2\x1d.controlplane.CPDeployRequestH\x00R\x06deploy\x121\n" +
	"\x04stop\x18\v \x01(\v2\x1b.controlplane.CPStopRequestH\x00R\x04stop\x12:\n" +
	"\arestart\x18\f \x01(\v2\x1e.controlplane.CPRestartRequestH\x00R\arestart\x12J\n" +
	"\rupdate_config\x18\r \x01(\v2#.controlplane.CPUpdateConfigRequestH\x00R\fupdateConfig\x12C\n" +
	"\vstream_logs\x18\x0e \x01(\v2 .controlplane.CPLogStreamRequestH\x00R\n" +
	"streamLogsB\t\n" +
	"\acommand\"\x80\x02\n" +
	"\x0fCPDeployRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bartifact\x18\x04 \x01(\tR\bartifact\x128\n" +
	"\n" +
	"build_type\x18\x05 \x01(\x0e2\x19.controlplane.CPBuildTypeR\tbuildType\x128\n" +
	"\x06config\x18\x06 \x01(\v2 .controlplane.CPDeploymentConfigR\x06config\"\xd4\x02\n" +
	"\x12CPDeploymentConfig\x12#\n" +
	"\rresource_tier\x18\x01 \x01(\tR\fresourceTier\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\x12H\n" +
	"\benv_vars\x18\x03 \x03(\v2-.controlplane.CPDeploymentConfig.EnvVarsEntryR\aenvVars\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\tR\tdependsOn\x12D\n" +
	"\fhealth_check\x18\x05 \x01(\v2!.controlplane.CPHealthCheckConfigR\vhealthCheck\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x01\n" +
	"\x13CPHealthCheckConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x05R\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12+\n" +
	"\x11healthy_threshold\x18\x05 \x01(\x05R\x10healthyThreshold\x12/\n" +
	"\x13unhealthy_threshold\x18\x06 \x01(\x05R\x12unhealthyThreshold\"s\n" +
	"\rCPStopRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"7\n" +
	"\x10CPRestartRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\"v\n" +
	"\x15CPUpdateConfigRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x128\n" +
	"\x06config\x18\x02 \x01(\v2 .controlplane.CPDeploymentConfigR\x06config\"\xf1\x01\n" +
	"\x12CPLogStreamRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x05R\ttailLines\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\x12%\n" +
	"\x0eservice_filter\x18\x05 \x01(\tR\rserviceFilter\x12;\n" +
	"\flevel_filter\x18\x06 \x01(\x0e2\x18.controlplane.CPLogLevelR\vlevelFilter\"\x87\x03\n" +
	"\fStatusReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.controlplane.DeploymentStatusR\x06status\x12!\n" +
	"\fcontainer_id\x18\x05 \x01(\tR\vcontainerId\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12B\n" +
	"\x0eresource_usage\x18\t \x01(\v2\x1b.controlplane.ResourceUsageR\rresourceUsage\"\xa7\x01\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12(\n" +
	"\x10network_rx_bytes\x18\x03 \x01(\x03R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\x04 \x01(\x03R\x0enetworkTxBytes\"4\n" +
	"\x0eStatusResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xf6\x02\n" +
	"\n" +
	"CPLogEntry\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12.\n" +
	"\x05level\x18\x05 \x01(\x0e2\x18.controlplane.CPLogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12B\n" +
	"\bmetadata\x18\a \x03(\v2&.controlplane.CPLogEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x10PushLogsResponse\x12)\n" +
	"\x10entries_received\x18\x01 \x01(\x03R\x0fentriesReceived*\x91\x01\n" +
	"\vCommandType\x12\x13\n" +
	"\x0fCOMMAND_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eCOMMAND_DEPLOY\x10\x01\x12\x10\n" +
	"\fCOMMAND_STOP\x10\x02\x12\x13\n" +
	"\x0fCOMMAND_RESTART\x10\x03\x12\x19\n" +
	"\x15COMMAND_UPDATE_CONFIG\x10\x04\x12\x17\n" +
	"\x13COMMAND_STREAM_LOGS\x10\x05*V\n" +
	"\vCPBuildType\x12\x19\n" +
	"\x15CP_BUILD_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CP_BUILD_TYPE_OCI\x10\x01\x12\x15\n" +
	"\x11CP_BUILD_TYPE_NIX\x10\x02*\xb3\x01\n" +
	"\x10DeploymentStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_PULLING\x10\x02\x12\x13\n" +
	"\x0fSTATUS_STARTING\x10\x03\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x04\x12\x13\n" +
	"\x0fSTATUS_STOPPING\x10\x05\x12\x12\n" +
	"\x0eSTATUS_STOPPED\x10\x06\x12\x11\n" +
	"\rSTATUS_FAILED\x10\a*f\n" +
	"\n" +
	"CPLogLevel\x12\x12\n" +
	"\x0eCP_LOG_UNKNOWN\x10\x00\x12\x10\n" +
	"\fCP_LOG_DEBUG\x10\x01\x12\x0f\n" +
	"\vCP_LOG_INFO\x10\x02\x12\x0f\n" +
	"\vCP_LOG_WARN\x10\x03\x12\x10\n" +
	"\fCP_LOG_ERROR\x10\x042\x98\x03\n" +
	"\x13ControlPlaneService\x12I\n" +
	"\bRegister\x12\x1d.controlplane.RegisterRequest\x1a\x1e.controlplane.RegisterResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.controlplane.HeartbeatRequest\x1a\x1f.controlplane.HeartbeatResponse\x12V\n" +
	"\rWatchCommands\x12\".controlplane.WatchCommandsRequest\x1a\x1f.controlplane.DeploymentCommand0\x01\x12H\n" +
	"\fReportStatus\x12\x1a.controlplane.StatusReport\x1a\x1c.controlplane.StatusResponse\x12F\n" +
	"\bPushLogs\x12\x18.controlplane.CPLogEntry\x1a\x1e.controlplane.PushLogsResponse(\x012\xa6\x01\n" +
	"\x06Health\x12L\n" +
	"\x05Check\x12 .controlplane.HealthCheckRequest\x1a!.controlplane.HealthCheckResponse\x12N\n" +
	"\x05Watch\x12 .controlplane.HealthCheckRequest\x1a!.controlplane.HealthCheckResponse0\x01B0Z.github.com/narvanalabs/control-plane/api/protob\x06proto3"

var (
	file_api_proto_controlplane_proto_rawDescOnce sync.Once
	file_api_proto_controlplane_proto_rawDescData []byte
)

func file_api_proto_controlplane_proto_rawDescGZIP() []byte {
	file_api_proto_controlplane_proto_rawDescOnce.Do(func() {
		file_api_proto_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_controlplane_proto_rawDesc), len(file_api_proto_controlplane_proto_rawDesc)))
	})
	return file_api_proto_controlplane_proto_rawDescData
}

var file_api_proto_controlplane_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_api_proto_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_proto_controlplane_proto_goTypes = []any{
	(CommandType)(0),                       // 0: controlplane.CommandType
	(CPBuildType)(0),                       // 1: controlplane.CPBuildType
	(DeploymentStatus)(0),                  // 2: controlplane.DeploymentStatus
	(CPLogLevel)(0),                        // 3: controlplane.CPLogLevel
	(HealthCheckResponse_ServingStatus)(0), // 4: controlplane.HealthCheckResponse.ServingStatus
	(*HealthCheckRequest)(nil),             // 5: controlplane.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 6: controlplane.HealthCheckResponse
	(*NodeInfo)(nil),                       // 7: controlplane.NodeInfo
	(*ResourceMetrics)(nil),                // 8: controlplane.ResourceMetrics
	(*RegisterRequest)(nil),                // 9: controlplane.RegisterRequest
	(*RegisterResponse)(nil),               // 10: controlplane.RegisterResponse
	(*NodeConfig)(nil),                     // 11: controlplane.NodeConfig
	(*HeartbeatRequest)(nil),               // 12: controlplane.HeartbeatRequest
	(*HeartbeatResponse)(nil),              // 13: controlplane.HeartbeatResponse
	(*WatchCommandsRequest)(nil),           // 14: controlplane.WatchCommandsRequest
	(*DeploymentCommand)(nil),              // 15: controlplane.DeploymentCommand
	(*CPDeployRequest)(nil),                // 16: controlplane.CPDeployRequest
	(*CPDeploymentConfig)(nil),             // 17: controlplane.CPDeploymentConfig
	(*CPHealthCheckConfig)(nil),            // 18: controlplane.CPHealthCheckConfig
	(*CPStopRequest)(nil),                  // 19: controlplane.CPStopRequest
	(*CPRestartRequest)(nil),               // 20: controlplane.CPRestartRequest
	(*CPUpdateConfigRequest)(nil),          // 21: controlplane.CPUpdateConfigRequest
	(*CPLogStreamRequest)(nil),             // 22: controlplane.CPLogStreamRequest
	(*StatusReport)(nil),                   // 23: controlplane.StatusReport
	(*ResourceUsage)(nil),                  // 24: controlplane.ResourceUsage
	(*StatusResponse)(nil),                 // 25: controlplane.StatusResponse
	(*CPLogEntry)(nil),                     // 26: controlplane.CPLogEntry
	(*PushLogsResponse)(nil),               // 27: controlplane.PushLogsResponse
	nil,                                    // 28: controlplane.CPDeploymentConfig.EnvVarsEntry
	nil,                                    // 29: controlplane.CPLogEntry.MetadataEntry
	(*timestamppb.Timestamp)(nil),          // 30: google.protobuf.Timestamp
}
var file_api_proto_controlplane_proto_depIdxs = []int32{
	4,  // 0: controlplane.HealthCheckResponse.status:type_name -> controlplane.HealthCheckResponse.ServingStatus
	8,  // 1: controlplane.NodeInfo.resources:type_name -> controlplane.ResourceMetrics
	7,  // 2: controlplane.RegisterRequest.node_info:type_name -> controlplane.NodeInfo
	11, // 3: controlplane.RegisterResponse.config:type_name -> controlplane.NodeConfig
	7,  // 4: controlplane.HeartbeatRequest.node_info:type_name -> controlplane.NodeInfo
	30, // 5: controlplane.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: controlplane.DeploymentCommand.type:type_name -> controlplane.CommandType
	30, // 7: controlplane.DeploymentCommand.deadline:type_name -> google.protobuf.Timestamp
	16, // 8: controlplane.DeploymentCommand.deploy:type_name -> controlplane.CPDeployRequest
	19, // 9: controlplane.DeploymentCommand.stop:type_name -> controlplane.CPStopRequest
	20, // 10: controlplane.DeploymentCommand.restart:type_name -> controlplane.CPRestartRequest
	21, // 11: controlplane.DeploymentCommand.update_config:type_name -> controlplane.CPUpdateConfigRequest
	22, // 12: controlplane.DeploymentCommand.stream_logs:type_name -> controlplane.CPLogStreamRequest
	1,  // 13: controlplane.CPDeployRequest.build_type:type_name -> controlplane.CPBuildType
	17, // 14: controlplane.CPDeployRequest.config:type_name -> controlplane.CPDeploymentConfig
	28, // 15: controlplane.CPDeploymentConfig.env_vars:type_name -> controlplane.CPDeploymentConfig.EnvVarsEntry
	18, // 16: controlplane.CPDeploymentConfig.health_check:type_name -> controlplane.CPHealthCheckConfig
	17, // 17: controlplane.CPUpdateConfigRequest.config:type_name -> controlplane.CPDeploymentConfig
	3,  // 18: controlplane.CPLogStreamRequest.level_filter:type_name -> controlplane.CPLogLevel
	2,  // 19: controlplane.StatusReport.status:type_name -> controlplane.DeploymentStatus
	30, // 20: controlplane.StatusReport.started_at:type_name -> google.protobuf.Timestamp
	24, // 21: controlplane.StatusReport.resource_usage:type_name -> controlplane.ResourceUsage
	30, // 22: controlplane.CPLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 23: controlplane.CPLogEntry.level:type_name -> controlplane.CPLogLevel
	29, // 24: controlplane.CPLogEntry.metadata:type_name -> controlplane.CPLogEntry.MetadataEntry
	9,  // 25: controlplane.ControlPlaneService.Register:input_type -> controlplane.RegisterRequest
	12, // 26: controlplane.ControlPlaneService.Heartbeat:input_type -> controlplane.HeartbeatRequest
	14, // 27: controlplane.ControlPlaneService.WatchCommands:input_type -> controlplane.WatchCommandsRequest
	23, // 28: controlplane.ControlPlaneService.ReportStatus:input_type -> controlplane.StatusReport
	26, // 29: controlplane.ControlPlaneService.PushLogs:input_type -> controlplane.CPLogEntry
	5,  // 30: controlplane.Health.Check:input_type -> controlplane.HealthCheckRequest
	5,  // 31: controlplane.Health.Watch:input_type -> controlplane.HealthCheckRequest
	10, // 32: controlplane.ControlPlaneService.Register:output_type -> controlplane.RegisterResponse
	13, // 33: controlplane.ControlPlaneService.Heartbeat:output_type -> controlplane.HeartbeatResponse
	15, // 34: controlplane.ControlPlaneService.WatchCommands:output_type -> controlplane.DeploymentCommand
	25, // 35: controlplane.ControlPlaneService.ReportStatus:output_type -> controlplane.StatusResponse
	27, // 36: controlplane.ControlPlaneService.PushLogs:output_type -> controlplane.PushLogsResponse
	6,  // 37: controlplane.Health.Check:output_type -> controlplane.HealthCheckResponse
	6,  // 38: controlplane.Health.Watch:output_type -> controlplane.HealthCheckResponse
	32, // [32:39] is the sub-list for method output_type
	25, // [25:32] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_proto_controlplane_proto_init() }
func file_api_proto_controlplane_proto_init() {
	if File_api_proto_controlplane_proto != nil {
		return
	}
	file_api_proto_controlplane_proto_msgTypes[10].OneofWrappers = []any{
		(*DeploymentCommand_Deploy)(nil),
		(*DeploymentCommand_Stop)(nil),
		(*DeploymentCommand_Restart)(nil),
		(*DeploymentCommand_UpdateConfig)(nil),
		(*DeploymentCommand_StreamLogs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_controlplane_proto_rawDesc), len(file_api_proto_controlplane_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_controlplane_proto_goTypes,
		DependencyIndexes: file_api_proto_controlplane_proto_depIdxs,
		EnumInfos:         file_api_proto_controlplane_proto_enumTypes,
		MessageInfos:      file_api_proto_controlplane_proto_msgTypes,
	}.Build()
	File_api_proto_controlplane_proto = out.File
	file_api_proto_controlplane_proto_goTypes = nil
	file_api_proto_controlplane_proto_depIdxs = nil
}
